name: tests

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install package
        run: python -m pip install -e .
      - name: Validate MethodBlocks
        run: methodblock validate-all
      - name: Compile MethodBlocks
        run: methodblock compile-all
      - name: Run tests
        run: pytest
